### PR TITLE
fix: cancel the type must be post

### PR DESCRIPTION
**Pull request by SigureMo**
增强自定义性，取消frontmatter 中一定要配置为 type=post  ，仅将该机制作为默认参数

### CODE REVIEW

**Comment by SigureMo** [comment]
要求每篇文章加上这个字段有些麻烦了吧，而且本身 filter 就是可以配置的，这个让用户自定义也是可以的吧，这个就直接作为默认值就好了

**Comment by ivandokov** [comment]
You are actually removing the option to set a filter from the pluginOptions and forcing always "post" type.

**Comment by ivandokov** [comment]
@SigureMo apologies for my previous comment. I didn't interpret the code correctly and I think your code is not a regression. This is why I deleted my comment but after that you closed the PR.

**Comment by SigureMo** [comment]
@ivandokov I think this PR may not be merged, because the author has not appeared for a long time. In addition, this workaround is not the best, it may be better as a feature request.:smile:

I am sorry for my broken English, there may be some inaccuracies.

**Pull request closed without merging**
